name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Setup PDM
        uses: pdm-project/setup-pdm@deb8d8a4e2a03aabcef6f2cc981923fc6b29ef99
        with:
          python-version: 3.13
          cache: true
      - name: Install project
        run: pdm install
      - name: build package
        run: |
          pdm build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          repository-url: https://test.pypi.org/legacy/
